version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/app
        networks:
            - internal
    node:
        build: ./docker/node
        volumes:
            - ./:/var/www/app
    fpm:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        networks:
            - internal
        volumes:
            - ./:/var/www/app
    database:
        image: postgres:14.1-alpine
        env_file: .env
        ports:
            - '5432:5432'
        networks:
            - internal
        volumes:
            - db:/var/lib/postgresql/data

networks:
    internal:
volumes:
    db:
